[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
amm = "L67WX11tRistNEPugzZn93eakCBQpvh8c4bZLYtpEku"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/leo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
