[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
escrow = "4hzLM36fkm3KKd9ywRxdqdUji62qDcGMCwiGt9i4TahQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/leo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
